try {
  const a = 1 + 2
}
catch (_error) {

}
